name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
            node-version: '20.x'
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ VirtueSky }}
          
      - name: Commit & Push
        run: |
          using: 'node20'
          git config user.name VirtueSky
          git config user.email virtuesky.0520@gmail.com
          git add -A .
          git commit -m "generated"
          git push
